# Generated by Django 3.2.3 on 2021-06-02 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='status',
            new_name='completion_status',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
